## Import NumPy as np

In [1]:
import numpy as np

## Create an array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Create an array of 10 fives

In [5]:
np.array([5,5,5,5,5,5,5,5,5,5])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### I can do it the above way or I can do it like this:

In [34]:
fives = np.ones(10)*5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## Create an array of integers from 10-50

In [9]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## Create an array of even integers from 10-50

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## Create a 3x3 matrix with values ranging from 0-8

In [14]:
ran = np.random.randint(0,8,9)

In [15]:
ran.reshape(3,3)

array([[6, 7, 2],
       [2, 2, 1],
       [2, 1, 7]])

## Use NumPy to generate a random number between 0-1

In [20]:
np.random.randn(1)

array([0.19714106])

## Create a matrix using the following statements and display it:

In [36]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Using the matrix you created above
### Get the sum of all the values in the mat matrix

In [25]:
mat.sum()

325

### Get the standard deviation of the values in the mat matrix

In [35]:
mat.std()

7.211102550927978

### Create a new matrix of 25 ones named mat1

In [28]:
mat1 = np.ones(25).reshape(5,5)

### Add the values of mat to those of mat1

In [29]:
mat + mat1

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.],
       [22., 23., 24., 25., 26.]])

### Multiply the values of mat to those of mat1

In [30]:
mat * mat1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])